name: Run E2E tests with Detox

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      downloadUrl:
        description: 'Link to Expo build url'
        required: true

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - name: Download build
        uses: suisei-cn/actions-download-file@v1
        id: downloadedApp
        with:
          url: ${{ github.event.inputs.downloadUrl }}
          target: bin/

      - name: Untar app build
        run: |
          cd bin
          ls -a
          for f in *.tar.gz; do tar -xvf "$f"; done
          ls
          cd ..

      - name: Setup Detox
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: Open Simulator & run tests
        run: yarn detox test --configuration ios
