name: Run E2E tests with Detox

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - name: Build app locally using EAS
        run: |
          eas build --local \
            --non-interactive \
            --output=./bin/easdetoxci.app \
            --platform=ios \
            --profile=development-sim

      - name: Setup detox
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: Open simulator & run tests
        run: |
          open -a Simulator.app
          sleep 10
          xcrun simctl install booted ./bin/easdetoxci.app
          sleep 15
          yarn detox test --configuration ios
