name: Run E2E tests with detox

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - name: Download build
        uses: suisei-cn/actions-download-file@v1
        id: downloadedApp
        with:
          url: ${{ secrets.EXPO_FILE_URL }}
          target: bin/

      - name: Untar app build
        run: |
          cd bin
          gunzip f8bf65aa-2bad-4983-8952-189e23adf392-98111e942ea945308df3157ae5405909.tar.gz
          tar xvfz f8bf65aa-2bad-4983-8952-189e23adf392-98111e942ea945308df3157ae5405909.tar.gz
          ls
          cd ..

      - name: Setup detox
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: Open simulator & run tests
        run: |
          open -a Simulator.app
          sleep 10
          xcrun simctl install booted ./bin/easdetoxci.app
          sleep 15
          yarn detox test --configuration ios
